version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: expense-db
    restart: always
    environment:
      POSTGRES_USER: emmanuel
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:

