name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
      - name: Generate Coverage Report
        run: ./gradlew jacocoTestReport
      - name: Build jar
        run: ./gradlew jar

      - name: Upload jar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: expense-sharing-system
          path: build/libs/*.jar

